-- ============================================
-- IMPROVED SCHEMA WITH PROPER SECURITY
-- ============================================

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Enable read access for all users" ON grounds;
DROP POLICY IF EXISTS "Enable insert access for all users" ON grounds;
DROP POLICY IF EXISTS "Enable update access for all users" ON grounds;
DROP POLICY IF EXISTS "Enable delete access for all users" ON grounds;
DROP POLICY IF EXISTS "Enable read access for all users" ON bookings;
DROP POLICY IF EXISTS "Enable insert access for all users" ON bookings;
DROP POLICY IF EXISTS "Enable update access for all users" ON bookings;
DROP POLICY IF EXISTS "Enable delete access for all users" ON bookings;

-- Create admin_users table for better security
CREATE TABLE IF NOT EXISTS admin_users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Insert admin users
INSERT INTO admin_users (username) VALUES ('wajahat'), ('usman'), ('rafay')
ON CONFLICT (username) DO NOTHING;

-- Enable RLS
ALTER TABLE grounds ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;

-- GROUNDS POLICIES (More Secure)
-- Anyone can read verified grounds
CREATE POLICY "Public can view verified grounds" 
ON grounds FOR SELECT 
USING (status = 'verified');

-- Anyone can insert (submit) new grounds
CREATE POLICY "Public can submit grounds" 
ON grounds FOR INSERT 
WITH CHECK (status = 'pending');

-- Only allow updates/deletes for now (you'll add admin auth later)
CREATE POLICY "Allow updates for all" 
ON grounds FOR UPDATE 
USING (true);

CREATE POLICY "Allow deletes for all" 
ON grounds FOR DELETE 
USING (true);

-- BOOKINGS POLICIES
-- Anyone can read their own bookings (for now, allow all reads)
CREATE POLICY "Public can view bookings" 
ON grounds FOR SELECT 
USING (true);

-- Anyone can create bookings
CREATE POLICY "Public can create bookings" 
ON bookings FOR INSERT 
WITH CHECK (true);

-- ADMIN USERS POLICIES
CREATE POLICY "Public can read admin list" 
ON admin_users FOR SELECT 
USING (true);

-- ============================================
-- INDEXES FOR BETTER PERFORMANCE
-- ============================================
CREATE INDEX IF NOT EXISTS idx_grounds_status ON grounds(status);
CREATE INDEX IF NOT EXISTS idx_grounds_city ON grounds(city);
CREATE INDEX IF NOT EXISTS idx_bookings_ground_id ON bookings("groundId");
CREATE INDEX IF NOT EXISTS idx_bookings_date ON bookings("bookingDate");
