-- Create grounds table
create table grounds (
  id bigint generated by default as identity primary key,
  "ownerName" text,
  "ownerEmail" text,
  "ownerPhone" text,
  "groundName" text,
  location text,
  city text,
  "groundType" text,
  dimensions text,
  "pricePerHour" numeric,
  facilities text[],
  "imageUrl" text,
  description text,
  status text default 'pending',
  rating numeric default 0,
  "reviewCount" integer default 0,
  "createdAt" timestamp with time zone default timezone('utc'::text, now())
);

-- Create bookings table
create table bookings (
  id bigint generated by default as identity primary key,
  "groundId" bigint references grounds(id),
  "playerName" text,
  "playerEmail" text,
  "playerPhone" text,
  "bookingDate" date,
  "timeSlot" text,
  "teamSize" integer,
  status text default 'confirmed',
  "createdAt" timestamp with time zone default timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
alter table grounds enable row level security;
alter table bookings enable row level security;

-- Create policies to allow public access (mirrors existing insecure Firebase setup)
-- WARNING: This is insecure. In production, you should add proper authentication.

create policy "Enable read access for all users" on grounds for select using (true);
create policy "Enable insert access for all users" on grounds for insert with check (true);
create policy "Enable update access for all users" on grounds for update using (true);
create policy "Enable delete access for all users" on grounds for delete using (true);

create policy "Enable read access for all users" on bookings for select using (true);
create policy "Enable insert access for all users" on bookings for insert with check (true);
create policy "Enable update access for all users" on bookings for update using (true);
create policy "Enable delete access for all users" on bookings for delete using (true);
